-- ==================== PORT_SUMMARY_VIEW ====================
-- Summary statistics for the entire port
CREATE VIEW PORT_SUMMARY_VIEW AS
SELECT 
    -- Total Counts
    (SELECT COUNT(*) FROM SHIPS) AS TOTAL_SHIPS,
    (SELECT COUNT(*) FROM ARRIVALS WHERE DEPARTUREDATE IS NULL) AS SHIPS_IN_PORT,
    (SELECT COUNT(*) FROM BERTHS) AS TOTAL_BERTHS,
    (SELECT COUNT(*) FROM BERTHS WHERE STATUS = 'Available') AS AVAILABLE_BERTHS,
    (SELECT COUNT(*) FROM CONTAINERS) AS TOTAL_CONTAINERS,
    
    -- Today's Activity
    (SELECT COUNT(*) FROM ARRIVALS WHERE CAST(ARRIVALDATE AS DATE) = CAST(GETDATE() AS DATE)) AS TODAY_ARRIVALS,
    (SELECT COUNT(*) FROM ARRIVALS WHERE CAST(DEPARTUREDATE AS DATE) = CAST(GETDATE() AS DATE)) AS TODAY_DEPARTURES,
    (SELECT COUNT(*) FROM CONTAINER_MOVEMENTS WHERE CAST(MOVEMENT_TIME AS DATE) = CAST(GETDATE() AS DATE)) AS TODAY_MOVEMENTS,
    
    -- Monthly Statistics
    (SELECT COUNT(*) FROM ARRIVALS WHERE MONTH(ARRIVALDATE) = MONTH(GETDATE()) AND YEAR(ARRIVALDATE) = YEAR(GETDATE())) AS MONTHLY_ARRIVALS,
    (SELECT COUNT(*) FROM CONTAINERS WHERE MONTH((SELECT ARRIVALDATE FROM ARRIVALS a WHERE a.ARRIVAL_REF = CONTAINERS.ARRIVAL_REF)) = MONTH(GETDATE())) AS MONTHLY_CONTAINERS,
    
    -- Performance Metrics
    (SELECT AVG(DATEDIFF(day, ARRIVALDATE, ISNULL(DEPARTUREDATE, GETDATE()))) FROM ARRIVALS) AS AVG_STAY_DAYS,
    (SELECT AVG(container_count) FROM (
        SELECT ARRIVAL_REF, COUNT(*) as container_count 
        FROM CONTAINERS 
        GROUP BY ARRIVAL_REF
    ) as subquery) AS AVG_CONTAINERS_PER_SHIP,
    
    -- Berth Utilization
    CAST(
        (SELECT COUNT(*) FROM BERTH_ALLOCATIONS ba 
         INNER JOIN ARRIVALS a ON ba.ARRIVAL_REF = a.ARRIVAL_REF 
         WHERE a.DEPARTUREDATE IS NULL) * 100.0 / 
        NULLIF((SELECT COUNT(*) FROM BERTHS), 0)
    AS DECIMAL(5,2)) AS BERTH_UTILIZATION_PERCENT,
    
    -- Container Status Breakdown
    (SELECT COUNT(*) FROM CONTAINERS WHERE STATUS = 'In Port') AS CONTAINERS_IN_PORT,
    (SELECT COUNT(*) FROM CONTAINERS WHERE STATUS = 'In Storage') AS CONTAINERS_IN_STORAGE,
    (SELECT COUNT(*) FROM CONTAINERS WHERE STATUS = 'Loaded') AS CONTAINERS_LOADED,
    
    -- Top Companies
    (SELECT TOP 1 COMPANY FROM SHIPS s 
     INNER JOIN ARRIVALS a ON s.SHIP_IMO = a.SHIP_IMO 
     GROUP BY COMPANY 
     ORDER BY COUNT(*) DESC) AS TOP_COMPANY,
    
    -- Busiest Berth
    (SELECT TOP 1 b.BERTHNAME FROM BERTHS b 
     INNER JOIN BERTH_ALLOCATIONS ba ON b.BERTH_CODE = ba.BERTH_CODE 
     GROUP BY b.BERTHNAME 
     ORDER BY COUNT(*) DESC) AS BUSIEST_BERTH;