USE [PortManagementSystemDb]
GO

-- add ship
IF OBJECT_ID('sp_AddShip', 'P') IS NOT NULL DROP PROCEDURE sp_AddShip;
GO
CREATE PROCEDURE sp_AddShip
    @SHIP_IMO VARCHAR(50),
    @SHIPNAME NVARCHAR(200),
    @COMPANY NVARCHAR(200)
AS
BEGIN
    INSERT INTO SHIPS (SHIP_IMO, SHIPNAME, COMPANY)
    VALUES (@SHIP_IMO, @SHIPNAME, @COMPANY);
END
GO

-- rigistration of arrival
IF OBJECT_ID('sp_RegisterArrival', 'P') IS NOT NULL DROP PROCEDURE sp_RegisterArrival;
GO
CREATE PROCEDURE sp_RegisterArrival
    @ARRIVAL_REF VARCHAR(50),
    @SHIP_IMO VARCHAR(50),
    @ARRIVALDATE DATE
AS
BEGIN
    INSERT INTO ARRIVALS (ARRIVAL_REF, SHIP_IMO, ARRIVALDATE)
    VALUES (@ARRIVAL_REF, @SHIP_IMO, @ARRIVALDATE);
END
GO

-- allocate berth
IF OBJECT_ID('sp_AllocateBerth', 'P') IS NOT NULL DROP PROCEDURE sp_AllocateBerth;
GO
CREATE PROCEDURE sp_AllocateBerth
    @ALLOC_CODE VARCHAR(50),
    @ARRIVAL_REF VARCHAR(50),
    @BERTH_CODE VARCHAR(50)
AS
BEGIN
    INSERT INTO BERTHALLOCATION (ALLOC_CODE, ARRIVAL_REF, BERTH_CODE)
    VALUES (@ALLOC_CODE, @ARRIVAL_REF, @BERTH_CODE);
    
    UPDATE BERTHS SET STATUS = N'reserved' WHERE BERTH_CODE = @BERTH_CODE;
END
GO

-- add container
IF OBJECT_ID('sp_AddContainer', 'P') IS NOT NULL DROP PROCEDURE sp_AddContainer;
GO
CREATE PROCEDURE sp_AddContainer
    @CONTAINER_NO VARCHAR(50),
    @ARRIVAL_REF VARCHAR(50),
    @TYPE NVARCHAR(50),
    @STATUS NVARCHAR(50)
AS
BEGIN
    INSERT INTO CONTAINERS (CONTAINER_NO, ARRIVAL_REF, TYPE, STATUS)
    VALUES (@CONTAINER_NO, @ARRIVAL_REF, @TYPE, @STATUS);
END
GO

-- check-out of ship
IF OBJECT_ID('sp_RegisterDeparture', 'P') IS NOT NULL DROP PROCEDURE sp_RegisterDeparture;
GO
CREATE PROCEDURE sp_RegisterDeparture
    @ARRIVAL_REF VARCHAR(50),
    @DEPARTUREDATE DATE
AS
BEGIN
    UPDATE ARRIVALS SET DEPARTUREDATE = @DEPARTUREDATE WHERE ARRIVAL_REF = @ARRIVAL_REF;
    
    DECLARE @BERTH VARCHAR(50);
    SELECT @BERTH = BERTH_CODE FROM BERTHALLOCATION WHERE ARRIVAL_REF = @ARRIVAL_REF;
    
    IF @BERTH IS NOT NULL
        UPDATE BERTHS SET STATUS = N'available' WHERE BERTH_CODE = @BERTH;
END
GO
